# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeometricTransformationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeometricTransformationWindow(object):
    def setupUi(self, GeometricTransformationWindow):
        GeometricTransformationWindow.setObjectName("GeometricTransformationWindow")
        GeometricTransformationWindow.resize(902, 686)
        GeometricTransformationWindow.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(GeometricTransformationWindow)
        self.pushButton.setGeometry(QtCore.QRect(780, 90, 93, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit.setGeometry(QtCore.QRect(240, 90, 521, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 201, 31))
        self.label_2.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 221, 51))
        self.label_3.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 140, 521, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(GeometricTransformationWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 140, 93, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label.setGeometry(QtCore.QRect(260, 20, 371, 41))
        self.label.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 380, 171, 61))
        self.label_4.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 390, 111, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_5.setGeometry(QtCore.QRect(20, 440, 131, 41))
        self.label_5.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 440, 111, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_6.setGeometry(QtCore.QRect(300, 390, 151, 41))
        self.label_6.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_5.setGeometry(QtCore.QRect(430, 390, 111, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_6.setGeometry(QtCore.QRect(430, 440, 111, 41))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_7.setGeometry(QtCore.QRect(300, 440, 151, 41))
        self.label_7.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_8.setGeometry(QtCore.QRect(20, 620, 151, 41))
        self.label_8.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 620, 111, 41))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_9.setGeometry(QtCore.QRect(290, 540, 81, 41))
        self.label_9.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_10.setGeometry(QtCore.QRect(290, 620, 81, 41))
        self.label_10.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_9.setGeometry(QtCore.QRect(420, 620, 111, 41))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_12.setGeometry(QtCore.QRect(570, 540, 141, 41))
        self.label_12.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 540, 111, 41))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_3 = QtWidgets.QPushButton(GeometricTransformationWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 620, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_11.setGeometry(QtCore.QRect(50, 190, 551, 21))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 351, 151))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_14.setGeometry(QtCore.QRect(420, 220, 151, 71))
        self.label_14.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_14.setObjectName("label_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_11.setGeometry(QtCore.QRect(630, 230, 241, 41))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_16 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_16.setGeometry(QtCore.QRect(20, 340, 221, 61))
        self.label_16.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_17.setGeometry(QtCore.QRect(300, 340, 171, 61))
        self.label_17.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_15.setGeometry(QtCore.QRect(570, 390, 151, 41))
        self.label_15.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_15.setObjectName("label_15")
        self.lineEdit_12 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_12.setGeometry(QtCore.QRect(710, 390, 111, 41))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_18 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_18.setGeometry(QtCore.QRect(570, 340, 201, 61))
        self.label_18.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_19.setGeometry(QtCore.QRect(570, 440, 141, 41))
        self.label_19.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_19.setObjectName("label_19")
        self.lineEdit_13 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_13.setGeometry(QtCore.QRect(710, 440, 111, 41))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_20 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_20.setGeometry(QtCore.QRect(20, 570, 201, 61))
        self.label_20.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_21.setGeometry(QtCore.QRect(300, 490, 201, 61))
        self.label_21.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_21.setObjectName("label_21")
        self.lineEdit_8 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_8.setGeometry(QtCore.QRect(420, 540, 111, 41))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_22 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_22.setGeometry(QtCore.QRect(570, 490, 201, 61))
        self.label_22.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_22.setObjectName("label_22")
        self.lineEdit_14 = QtWidgets.QLineEdit(GeometricTransformationWindow)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 540, 111, 41))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_23 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_23.setGeometry(QtCore.QRect(20, 490, 201, 61))
        self.label_23.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(GeometricTransformationWindow)
        self.label_24.setGeometry(QtCore.QRect(20, 540, 151, 41))
        self.label_24.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_24.setObjectName("label_24")
        self.frame = QtWidgets.QFrame(GeometricTransformationWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 901, 691))
        self.frame.setStyleSheet("border-image: url(:/images/images/11.jpg);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.lineEdit_3.raise_()
        self.label_5.raise_()
        self.lineEdit_4.raise_()
        self.label_6.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.lineEdit_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.lineEdit_9.raise_()
        self.label_12.raise_()
        self.lineEdit_10.raise_()
        self.pushButton_3.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lineEdit_11.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_15.raise_()
        self.lineEdit_12.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.lineEdit_13.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.lineEdit_8.raise_()
        self.label_22.raise_()
        self.lineEdit_14.raise_()
        self.label_23.raise_()
        self.label_24.raise_()

        self.retranslateUi(GeometricTransformationWindow)
        QtCore.QMetaObject.connectSlotsByName(GeometricTransformationWindow)

    def retranslateUi(self, GeometricTransformationWindow):
        _translate = QtCore.QCoreApplication.translate
        GeometricTransformationWindow.setWindowTitle(_translate("GeometricTransformationWindow", "Form"))
        self.pushButton.setText(_translate("GeometricTransformationWindow", "选择路径"))
        self.label_2.setText(_translate("GeometricTransformationWindow", "请您选择要处理的图像："))
        self.label_3.setText(_translate("GeometricTransformationWindow", "如需保存，请输入存储位置："))
        self.pushButton_2.setText(_translate("GeometricTransformationWindow", "选择路径"))
        self.label.setText(_translate("GeometricTransformationWindow", "欢迎使用图像几何变换功能"))
        self.label_4.setText(_translate("GeometricTransformationWindow", "请输入放大倍数："))
        self.label_5.setText(_translate("GeometricTransformationWindow", "请输入缩小倍数："))
        self.label_6.setText(_translate("GeometricTransformationWindow", "输入梯形边斜率："))
        self.label_7.setText(_translate("GeometricTransformationWindow", "输入梯形种类："))
        self.label_8.setText(_translate("GeometricTransformationWindow", "请输入旋转角度："))
        self.label_9.setText(_translate("GeometricTransformationWindow", "输入x偏移："))
        self.label_10.setText(_translate("GeometricTransformationWindow", "输入y偏移："))
        self.label_12.setText(_translate("GeometricTransformationWindow", "输入参考轴(x或y)："))
        self.pushButton_3.setText(_translate("GeometricTransformationWindow", "执行"))
        self.label_13.setText(_translate("GeometricTransformationWindow", "1: 按比例缩小  2: 按比例放大  3: 水平外凹\n"
"\n"
"4: 水平外凸    5: 梯形变形    6: 三角形变形\n"
"\n"
"7: S形变形     8: 图片旋转    9: 图片平移\n"
"\n"
"10: 图片翻转\n"
"\n"
""))
        self.label_14.setText(_translate("GeometricTransformationWindow", "请输入数字 1—10 ，\n"
"选择你需要的变换\n"
"(按\'Q\'或\'q\'退出)："))
        self.label_16.setText(_translate("GeometricTransformationWindow", "如果选择了 1 缩小 或 2 放大 ："))
        self.label_17.setText(_translate("GeometricTransformationWindow", "如果选择了 5 梯形形变："))
        self.label_15.setText(_translate("GeometricTransformationWindow", "输入三角边斜率："))
        self.label_18.setText(_translate("GeometricTransformationWindow", "如果选择了 6 三角形形变："))
        self.label_19.setText(_translate("GeometricTransformationWindow", "输入三角形形种类："))
        self.label_20.setText(_translate("GeometricTransformationWindow", "如果选择了 8 图片旋转："))
        self.label_21.setText(_translate("GeometricTransformationWindow", "如果选择了 9 图片平移："))
        self.label_22.setText(_translate("GeometricTransformationWindow", "如果选择了 10 图片翻转："))
        self.label_23.setText(_translate("GeometricTransformationWindow", "如果选择了 7 S型变化："))
        self.label_24.setText(_translate("GeometricTransformationWindow", "请输入变换强度："))


import images_rc
