# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 851, 561))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-image: url(:/images/images/5.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 50, 261, 211))
        self.calendarWidget.setAccessibleName("")
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("background :rgb(216, 216, 216);")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 310, 271, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 380, 201, 81))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        self.menu_13 = QtWidgets.QMenu(self.menubar)
        self.menu_13.setObjectName("menu_13")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondsadsad = QtWidgets.QAction(MainWindow)
        self.actiondsadsad.setObjectName("actiondsadsad")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setCheckable(False)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.actioncanny = QtWidgets.QAction(MainWindow)
        self.actioncanny.setObjectName("actioncanny")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.actionotsu = QtWidgets.QAction(MainWindow)
        self.actionotsu.setObjectName("actionotsu")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.action_20 = QtWidgets.QAction(MainWindow)
        self.action_20.setObjectName("action_20")
        self.action_21 = QtWidgets.QAction(MainWindow)
        self.action_21.setObjectName("action_21")
        self.action_23 = QtWidgets.QAction(MainWindow)
        self.action_23.setObjectName("action_23")
        self.action_27 = QtWidgets.QAction(MainWindow)
        self.action_27.setObjectName("action_27")
        self.action_29 = QtWidgets.QAction(MainWindow)
        self.action_29.setObjectName("action_29")
        self.action_31 = QtWidgets.QAction(MainWindow)
        self.action_31.setObjectName("action_31")
        self.action_33 = QtWidgets.QAction(MainWindow)
        self.action_33.setObjectName("action_33")
        self.actionS = QtWidgets.QAction(MainWindow)
        self.actionS.setObjectName("actionS")
        self.action_36 = QtWidgets.QAction(MainWindow)
        self.action_36.setObjectName("action_36")
        self.action_38 = QtWidgets.QAction(MainWindow)
        self.action_38.setObjectName("action_38")
        self.actionx = QtWidgets.QAction(MainWindow)
        self.actionx.setObjectName("actionx")
        self.actiony = QtWidgets.QAction(MainWindow)
        self.actiony.setObjectName("actiony")
        self.action3_3 = QtWidgets.QAction(MainWindow)
        self.action3_3.setObjectName("action3_3")
        self.action3_4 = QtWidgets.QAction(MainWindow)
        self.action3_4.setObjectName("action3_4")
        self.action5_5 = QtWidgets.QAction(MainWindow)
        self.action5_5.setObjectName("action5_5")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu_2.addAction(self.action_3)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.action_14)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionotsu)
        self.menu_4.addAction(self.action)
        self.menu_5.addAction(self.action_8)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.action_9)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.action_11)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.action_13)
        self.menu_6.addAction(self.actioncanny)
        self.menu_13.addAction(self.action3_3)
        self.menu_13.addSeparator()
        self.menu_13.addAction(self.action3_4)
        self.menu_13.addSeparator()
        self.menu_13.addAction(self.action5_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_13.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "欢迎使用本数字图像处理组合包\n"
"\n"
"\n"
"请在最上方的菜单栏选择自己想要的功能\n"
""))
        self.label_2.setText(_translate("MainWindow", "祝您使用愉快"))
        self.menu.setTitle(_translate("MainWindow", "首页"))
        self.menu_2.setTitle(_translate("MainWindow", "灰度化、均衡化操作"))
        self.menu_3.setTitle(_translate("MainWindow", "二值化"))
        self.menu_4.setTitle(_translate("MainWindow", "图像的几何变换"))
        self.menu_5.setTitle(_translate("MainWindow", "图像分割"))
        self.menu_6.setTitle(_translate("MainWindow", "图像边缘检测"))
        self.menu_7.setTitle(_translate("MainWindow", "关于"))
        self.menu_8.setTitle(_translate("MainWindow", "帮助"))
        self.menu_13.setTitle(_translate("MainWindow", "滤波器"))
        self.actiondsadsad.setText(_translate("MainWindow", "dsadsad"))
        self.action_3.setText(_translate("MainWindow", "图像灰度化"))
        self.action_4.setText(_translate("MainWindow", "图像均衡化"))
        self.actioncanny.setText(_translate("MainWindow", "canny"))
        self.action_8.setText(_translate("MainWindow", "全局分割"))
        self.action_9.setText(_translate("MainWindow", "动态分割"))
        self.action_11.setText(_translate("MainWindow", "区域生长"))
        self.action_13.setText(_translate("MainWindow", "分水岭"))
        self.action_14.setText(_translate("MainWindow", "自选阈值"))
        self.actionotsu.setText(_translate("MainWindow", "otsu 算法"))
        self.action_18.setText(_translate("MainWindow", "缩小"))
        self.action_20.setText(_translate("MainWindow", "放大"))
        self.action_21.setText(_translate("MainWindow", "水平外凹"))
        self.action_23.setText(_translate("MainWindow", "水平外凸"))
        self.action_27.setText(_translate("MainWindow", "水平梯形形变"))
        self.action_29.setText(_translate("MainWindow", "竖直梯形形变"))
        self.action_31.setText(_translate("MainWindow", "直角三角形形变"))
        self.action_33.setText(_translate("MainWindow", "等腰三角形形变"))
        self.actionS.setText(_translate("MainWindow", "S形变形"))
        self.action_36.setText(_translate("MainWindow", "图片旋转"))
        self.action_38.setText(_translate("MainWindow", "图片平移"))
        self.actionx.setText(_translate("MainWindow", "x 轴翻转"))
        self.actiony.setText(_translate("MainWindow", "y 轴翻转"))
        self.action3_3.setText(_translate("MainWindow", "3*3中值滤波"))
        self.action3_4.setText(_translate("MainWindow", "3*3均值滤波"))
        self.action5_5.setText(_translate("MainWindow", "5*5高斯滤波"))
        self.action.setText(_translate("MainWindow", "立刻进行"))


import images_rc
