# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegionalGrowthWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegionalGrowthWindow(object):
    def setupUi(self, RegionalGrowthWindow):
        RegionalGrowthWindow.setObjectName("RegionalGrowthWindow")
        RegionalGrowthWindow.resize(902, 686)
        RegionalGrowthWindow.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(RegionalGrowthWindow)
        self.pushButton.setGeometry(QtCore.QRect(780, 90, 93, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(RegionalGrowthWindow)
        self.lineEdit.setGeometry(QtCore.QRect(240, 90, 521, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(RegionalGrowthWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 201, 31))
        self.label_2.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(RegionalGrowthWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 221, 51))
        self.label_3.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(RegionalGrowthWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 140, 521, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(RegionalGrowthWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 140, 93, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(RegionalGrowthWindow)
        self.frame.setGeometry(QtCore.QRect(10, 260, 431, 401))
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-image: url(:/images/images/2.jpg);\n"
"border-image: url(:/images/images/touming.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(RegionalGrowthWindow)
        self.frame_2.setGeometry(QtCore.QRect(460, 260, 431, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(RegionalGrowthWindow)
        self.label.setGeometry(QtCore.QRect(190, 20, 541, 41))
        self.label.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(RegionalGrowthWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 200, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(RegionalGrowthWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 200, 131, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(RegionalGrowthWindow)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 171, 61))
        self.label_4.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(RegionalGrowthWindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 200, 221, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(RegionalGrowthWindow)
        self.label_5.setGeometry(QtCore.QRect(410, 200, 81, 41))
        self.label_5.setStyleSheet("font: 10pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(RegionalGrowthWindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(490, 200, 91, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame_3 = QtWidgets.QFrame(RegionalGrowthWindow)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 901, 681))
        self.frame_3.setStyleSheet("border-image: url(:/images/images/9.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_4.raise_()
        self.lineEdit_3.raise_()
        self.label_5.raise_()
        self.lineEdit_4.raise_()

        self.retranslateUi(RegionalGrowthWindow)
        QtCore.QMetaObject.connectSlotsByName(RegionalGrowthWindow)

    def retranslateUi(self, RegionalGrowthWindow):
        _translate = QtCore.QCoreApplication.translate
        RegionalGrowthWindow.setWindowTitle(_translate("RegionalGrowthWindow", "Form"))
        self.pushButton.setText(_translate("RegionalGrowthWindow", "选择路径"))
        self.label_2.setText(_translate("RegionalGrowthWindow", "请您选择要处理的图像："))
        self.label_3.setText(_translate("RegionalGrowthWindow", "如需保存，请输入存储位置："))
        self.pushButton_2.setText(_translate("RegionalGrowthWindow", "选择路径"))
        self.label.setText(_translate("RegionalGrowthWindow", "欢迎使用图像区域生长，分水岭算法功能"))
        self.pushButton_3.setText(_translate("RegionalGrowthWindow", "分水岭算法"))
        self.pushButton_4.setText(_translate("RegionalGrowthWindow", "区域生长"))
        self.label_4.setText(_translate("RegionalGrowthWindow", "请输入区域生长起点\n"
"(使用空格隔开)："))
        self.label_5.setText(_translate("RegionalGrowthWindow", "输入阈值："))


import images_rc
